"""Add full_name and mobile_number to User

Revision ID: 45ff0e9bba75
Revises: add2d4e1d4f9
Create Date: 2026-07-18 00:10:15.261769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ff0e9bba75'
down_revision: Union[str, Sequence[str], None] = 'add2d4e1d4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_number')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
