import random
from faker import Faker
from sqlalchemy.orm import Session
from app.database.session import SessionLocal, engine, Base
from app.models.user import User, UserProfile
from app.models.financial import FinancialProfile
from app.models.transaction import Transaction
from app.models.workflow import Assessment
from app.auth.security import get_password_hash

fake = Faker()

def seed_database():
    db = SessionLocal()
    
    # Check if seeded
    if db.query(User).count() > 0:
        print("Database already seeded.")
        db.close()
        return

    print("Starting database seed...")
    
    # 1. The Stable Earner
    # 2. The High-Risk Spender
    # 3. The Gig Worker
    # 4. The Young Professional
    # 5. The Small Business Owner
    # 6. The Wealthy Executive
    # 7. The Struggling Student
    # 8. The Retiree
    # 9. The Frugal Saver
    # 10. The Serial Defaulter (Fraud Flag)
    
    personas = [
        {"name": "Stable Earner", "income": 120000, "expenses": 60000, "savings": 250000, "rent": 25000, "score": 850},
        {"name": "High-Risk Spender", "income": 150000, "expenses": 140000, "savings": 5000, "rent": 45000, "score": 450},
        {"name": "Gig Worker", "income": 45000, "expenses": 35000, "savings": 12000, "rent": 15000, "score": 680},
        {"name": "Young Professional", "income": 80000, "expenses": 60000, "savings": 40000, "rent": 30000, "score": 720},
        {"name": "Small Business Owner", "income": 250000, "expenses": 180000, "savings": 500000, "rent": 60000, "score": 810},
        {"name": "Wealthy Executive", "income": 500000, "expenses": 200000, "savings": 2500000, "rent": 80000, "score": 920},
        {"name": "Struggling Student", "income": 15000, "expenses": 18000, "savings": 500, "rent": 8000, "score": 350},
        {"name": "Retiree", "income": 60000, "expenses": 40000, "savings": 800000, "rent": 10000, "score": 890},
        {"name": "Frugal Saver", "income": 50000, "expenses": 20000, "savings": 150000, "rent": 12000, "score": 830},
        {"name": "Suspicious Activity", "income": 80000, "expenses": 95000, "savings": 0, "rent": 40000, "score": 250, "fraud": True},
    ]

    for p in personas:
        # Create User
        email = f"{p['name'].replace(' ', '.').lower()}@example.com"
        user = User(
            email=email,
            hashed_password=get_password_hash("password123"),
            full_name=p['name'],
            mobile_number=fake.phone_number()
        )
        db.add(user)
        db.commit()
        db.refresh(user)

        # Create Profile
        profile = UserProfile(
            user_id=str(user.id),
            occupation=fake.job(),
            annual_income=p['income'] * 12,
            employment_type="Full Time" if p['income'] > 50000 else "Part Time",
            city=fake.city(),
            state=fake.state(),
            age=random.randint(22, 65)
        )
        db.add(profile)
        
        # Create Financial Profile
        fin_profile = FinancialProfile(
            user_id=user.id,
            monthly_income=p['income'],
            monthly_expenses=p['expenses'],
            savings=p['savings'],
            rent=p['rent'],
            utilities=p['rent'] * 0.15,
            loan_amount=p['expenses'] * 0.2,
            emi=p['expenses'] * 0.1
        )
        db.add(fin_profile)
        
        # Create Transactions
        for _ in range(5):
            tx = Transaction(
                user_id=str(user.id),
                transaction_type="debit",
                category="Food",
                amount=random.uniform(100, 2000),
                description=fake.company()
            )
            db.add(tx)
            
        # Create Assessment
        is_fraud = p.get('fraud', False)
        cash_flow = p['income'] - p['expenses']
        
        assessment = Assessment(
            user_id=str(user.id),
            score=p['score'],
            fhi=int(p['score'] / 10),
            risk_level="High" if p['score'] < 500 else "Low",
            repayment_probability="90%" if p['score'] > 700 else "40%",
            loan_recommendation={
                "status": "Approved" if p['score'] > 600 else "Declined",
                "suggested_interest_rate": 10.5 if p['score'] > 700 else 18.5,
                "suggested_loan_amount": p['income'] * 3
            },
            fraud_flags=["High velocity transactions detected"] if is_fraud else [],
            explanation={
                "positive_factors": ["High savings"] if p['savings'] > 100000 else [],
                "negative_factors": ["High expenses"] if cash_flow < 0 else [],
                "behavior_score": int(p['score'] / 10),
                "income_stability": "Stable" if cash_flow > 0 else "Volatile",
                "reason_behind_score": "Generated by Demo Seeder.",
                "shap_data": [
                    {"name": "Cash Flow", "impact": 40},
                    {"name": "Savings", "impact": 30}
                ]
            }
        )
        db.add(assessment)
        db.commit()

    print("Seed complete. 10 users added.")
    db.close()

if __name__ == "__main__":
    seed_database()
